/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yanwanfu_hellojni_JniBridge */

#ifndef _Included_com_yanwanfu_hellojni_JniBridge
#define _Included_com_yanwanfu_hellojni_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yanwanfu_hellojni_JniBridge
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yanwanfu_hellojni_JniBridge_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
